const data = [
  {
    title: "Associate Software Engineer",
    qualification: {
      title: "Bachelors in Computer Science",
    },
    photoUrl: ["https://placeimg.com/640/480/arch", "https://placeimg.com/640/480/arch", "https://placeimg.com/640/480/arch", "https://placeimg.com/640/480/arch"],
    certificate: { title: "" },
    experienceListId: 3,
    companyBanner: require("../../assets/images/sample/jobimg-2.png"),
    location: "Dubai",
    company: "wolf.io",
    endDate: "Ends in 10 days",
    type: "Full Time",
    salary: "25,000 - 30,000 AED",
    imgUrl: require("../../assets/images/sample/jobimg-2.png"),
    featured: true,
    messaged: "MESSAGED",
    applied: "APPLIED",
    companyLogo: require("../../assets/images/sample/jobimg-2.png"),
    shortListJob: ["1"],
    jobBrief:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi cum molestias voluptate, dolorum amet corrupti expedita perferendis, velit sit quisquam ut odio obcaecati nam? Tenetur temporibus itaque non dignissimos. Nam?",
  },
  {
    title: "School Teacher",
    location: "Dubai",
    company: "Al Buraq School",
    endDate: "Ends in 2 days",
    type: "Full Time",
    salary: "10,000 - 15,000 AED",
    imgUrl: require("../../assets/images/sample/jobimg-1.png"),
    featured: true,
    jobBrief:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi cum molestias voluptate, dolorum amet corrupti expedita perferendis, velit sit quisquam ut odio obcaecati nam? Tenetur temporibus itaque non dignissimos. Nam?",
  },
  {
    title: "Security Guard",
    location: "Dubai",
    company: "Delta",
    endDate: "Ends in 1 day",
    type: "Contract",
    salary: "5000 - 6000 AED",
    imgUrl: require("../../assets/images/sample/jobimg-3.png"),
    featured: false,
    jobBrief:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi cum molestias voluptate, dolorum amet corrupti expedita perferendis, velit sit quisquam ut odio obcaecati nam? Tenetur temporibus itaque non dignissimos. Nam?",
  },
  {
    title: "Bus Driver",
    location: "Dubai",
    company: "Delta",
    endDate: "Ends in 6 days",
    type: "Contract",
    salary: "4000 - 5000 AED",
    imgUrl: require("../../assets/images/sample/jobimg-3.png"),
    featured: false,
    jobBrief:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi cum molestias voluptate, dolorum amet corrupti expedita perferendis, velit sit quisquam ut odio obcaecati nam? Tenetur temporibus itaque non dignissimos. Nam?",
  },
  {
    title: "Truck Driver",
    location: "Dubai",
    company: "Delta",
    endDate: "Ends in 29 days",
    type: "Contract",
    salary: "5500 - 6000 AED",
    imgUrl: require("../../assets/images/sample/jobimg-3.png"),
    featured: false,
    jobBrief:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi cum molestias voluptate, dolorum amet corrupti expedita perferendis, velit sit quisquam ut odio obcaecati nam? Tenetur temporibus itaque non dignissimos. Nam?",
  },
  {
    title: "Front Desk Associate",
    location: "Dubai",
    company: "Delta",
    endDate: "Ends in 45 days",
    type: "Part Time",
    salary: "8000 - 10,000 AED",
    imgUrl: require("../../assets/images/sample/jobimg-3.png"),
    featured: false,
    jobBrief:
      "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi cum molestias voluptate, dolorum amet corrupti expedita perferendis, velit sit quisquam ut odio obcaecati nam? Tenetur temporibus itaque non dignissimos. Nam?",
  },
];
export default data;
